### ISSUE TITLE
assets/bones/all.js fails to load

### ISSUE THREAD

**Issue by wwhurley** [developmentseed/bones#46] opened 2012-03-05 19:50 UTC
In server.prototype.initializeAssets (servers/Route.bones) the following needs to be changed:

-this.get('/assets/bones/all.js', this.assets.all);
+this.get('/assets/bones/all.js', this.assets.all.handler);

Otherwise any request to assets/bones/all.js gives the following error:

TypeError: string is not a function
    at String.CALL_NON_FUNCTION (native)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:270:11)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Documents/workspaces/Sitemanager/UI/node_modules/bones/node_modules/express/lib/router/index.js:277:9)

**Comment by springmeyer** [comment] 2012-03-07 00:33
can you provide a testcase of how you triggered this problem?

**Comment by wwhurley** [comment] 2012-03-07 15:02
Sure. The following demonstrates it:
- git clone https://github.com/developmentseed/bones.git
- cd bones/examples/simple 
- add dependency for "bones" : "latest" to the package.json
- run npm install
- run ./index.js
- open http://localhost:3000 
- See 500 error for http://localhost:3000/assets/bones/all.js, you'll also see the error in the terminal window or you can navigate directly to http://localhost:3000/assets/bones/all.js in your browser and see the error:

TypeError: object is not a function
    at Object.CALL_NON_FUNCTION (native)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:270:11)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)
    at callbacks (/Users/william/Sites/bonestwo/examples/simple/node_modules/bones/node_modules/express/lib/router/index.js:277:9)

I compared the file in the repository to the version that ships with Tilemill and noticed that in the working version that the syntax is this.get('/assets/bones/all.js', this.assets.all.handler) and not this.get('/assets/bones/all.js', this.assets.all).

I assume there was some regression at some point in one of the edits to master, though I haven't looked through the commits to see when that might have occurred.

**Comment by AdrianRossouw** [comment] 2012-05-03 01:13
i can confirm this issue.

the upstream mirror library changed : 

https://github.com/developmentseed/mirror/commit/5bc93ebc4d12902e6f0164a0b5adf299ef8d2215

this only affects the 2.x branch afaik, because it uses a different version of mirror.

**Comment by robotastic** [comment] 2012-06-28 11:02
I had the exact same problem. Thanks for catching and the fix.

**Comment by miccolis** [comment] 2012-07-27 14:08
Fixed in 210048f0d443bc1c62cb4a491fa675aa7806d074

**Closed as completed by miccolis** 2012-07-27 14:08 UTC
